// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPttgF3L70IP2mkE0idWBPBn1O-BF2YEI',
    appId: '1:468657209152:web:5be7c121d8bbdb0a9a84a5',
    messagingSenderId: '468657209152',
    projectId: 'serkom1',
    authDomain: 'serkom1.firebaseapp.com',
    storageBucket: 'serkom1.appspot.com',
    measurementId: 'G-04YBWE542S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qNGO1wEaiP72llEy7cvnA23X7IqD_3Y',
    appId: '1:468657209152:android:9a3bee9ae83c09e79a84a5',
    messagingSenderId: '468657209152',
    projectId: 'serkom1',
    storageBucket: 'serkom1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDhNTk0dkmg-PYrwApveiv7Ci-xhx3Ag',
    appId: '1:468657209152:ios:df4fe08483e243e29a84a5',
    messagingSenderId: '468657209152',
    projectId: 'serkom1',
    storageBucket: 'serkom1.appspot.com',
    iosBundleId: 'com.example.serkom1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDhNTk0dkmg-PYrwApveiv7Ci-xhx3Ag',
    appId: '1:468657209152:ios:df4fe08483e243e29a84a5',
    messagingSenderId: '468657209152',
    projectId: 'serkom1',
    storageBucket: 'serkom1.appspot.com',
    iosBundleId: 'com.example.serkom1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPttgF3L70IP2mkE0idWBPBn1O-BF2YEI',
    appId: '1:468657209152:web:05fdd0970888ed019a84a5',
    messagingSenderId: '468657209152',
    projectId: 'serkom1',
    authDomain: 'serkom1.firebaseapp.com',
    storageBucket: 'serkom1.appspot.com',
    measurementId: 'G-4N5TJVWJV3',
  );
}
